package oppo

type IndexResponse struct {
	Errno int `json:"errno"`
	Data  struct {
		Total int   `json:"total"`
		Apps  []App `json:"rows"`
	} `json:"data"`
}

type App struct {
	AppID                 string      `json:"app_id"`
	PkgName               string      `json:"pkg_name"`
	Type                  string      `json:"type"`
	Sign                  string      `json:"sign"`
	DevID                 string      `json:"dev_id"`
	AppSecret             string      `json:"app_secret"`
	ServerSecret          string      `json:"server_secret"`
	AppKey                string      `json:"app_key"`
	UpdateTime            string      `json:"update_time"`
	AppCreateTime         string      `json:"app_create_time"`
	SecondCategoryID      string      `json:"second_category_id"`
	ThirdCategoryID       string      `json:"third_category_id"`
	AppName               string      `json:"app_name"`
	IsFreeze              string      `json:"is_freeze"`
	FreezeReason          interface{} `json:"freeze_reason"`
	RefuseReason          string      `json:"refuse_reason"`
	TagList               interface{} `json:"tag_list"`
	IsBusiness            string      `json:"is_business"`
	GameType              string      `json:"game_type"`
	CopyrightURL          string      `json:"copyright_url"`
	SpecialURL            string      `json:"special_url"`
	SpecialFileURL        string      `json:"special_file_url"`
	FreezeFile            interface{} `json:"freeze_file"`
	BusinessUsername      string      `json:"business_username"`
	BusinessEmail         string      `json:"business_email"`
	BusinessMobile        string      `json:"business_mobile"`
	BusinessQq            interface{} `json:"business_qq"`
	BusinessPosition      interface{} `json:"business_position"`
	BusinessAddress       interface{} `json:"business_address"`
	FreezeAdvice          interface{} `json:"freeze_advice"`
	AppType               string      `json:"app_type"`
	AppRealType           string      `json:"app_real_type"`
	AdType                string      `json:"ad_type"`
	DevName               string      `json:"dev_name"`
	ElectronicCertURL     string      `json:"electronic_cert_url"`
	IcpURL                string      `json:"icp_url"`
	RelationAppID         string      `json:"relation_app_id"`
	VersionID             string      `json:"version_id"`
	VersionCode           string      `json:"version_code"`
	VersionName           string      `json:"version_name"`
	ApkURL                string      `json:"apk_url"`
	ApkSize               string      `json:"apk_size"`
	ApkMd5                string      `json:"apk_md5"`
	HeaderMd5             string      `json:"header_md5"`
	Channel               string      `json:"channel"`
	PackagePermission     string      `json:"package_permission"`
	Resolution            interface{} `json:"resolution"`
	VersionType           string      `json:"version_type"`
	CreateTime            string      `json:"create_time"`
	MinSdkVersion         string      `json:"min_sdk_version"`
	TargetSdkVersion      string      `json:"target_sdk_version"`
	VerSecondCategoryID   string      `json:"ver_second_category_id"`
	VerThirdCategoryID    string      `json:"ver_third_category_id"`
	ReleaseType           string      `json:"release_type"`
	ReleaseOverType       string      `json:"release_over_type"`
	PhoneSupport          string      `json:"phone_support"`
	PhoneSupportVersion   string      `json:"phone_support_version"`
	IosLink               string      `json:"ios_link"`
	AdaptiveEquipment     string      `json:"adaptive_equipment"`
	AdaptiveType          string      `json:"adaptive_type"`
	VersionDevice         string      `json:"version_device"`
	ApkFullURL            string      `json:"apk_full_url"`
	OnlineType            string      `json:"online_type"`
	ScheOnlineTime        interface{} `json:"sche_online_time"`
	TestType              string      `json:"test_type"`
	TestStartTime         string      `json:"test_start_time"`
	TestEndTime           string      `json:"test_end_time"`
	PlayerCustomerEmail   interface{} `json:"player_customer_email"`
	PlayerCustomerPhone   interface{} `json:"player_customer_phone"`
	PlayerCustomerQq      interface{} `json:"player_customer_qq"`
	IsSignature           string      `json:"is_signature"`
	IsPreDownload         string      `json:"is_pre_download"`
	CustomerContact       interface{} `json:"customer_contact"`
	Lang                  string      `json:"lang"`
	IconURL               string      `json:"icon_url"`
	IconMd5               string      `json:"icon_md5"`
	Summary               string      `json:"summary"`
	DetailDesc            string      `json:"detail_desc"`
	UpdateDesc            string      `json:"update_desc"`
	AppSubname            string      `json:"app_subname"`
	TestDesc              string      `json:"test_desc"`
	VideoURL              string      `json:"video_url"`
	PicURL                string      `json:"pic_url"`
	PackagePermissionDesc string      `json:"package_permission_desc"`
	VideoPicURL           interface{} `json:"video_pic_url"`
	CoverURL              interface{} `json:"cover_url"`
	LandscapePicURL       string      `json:"landscape_pic_url"`
	PrivacySourceURL      string      `json:"privacy_source_url"`
	ReleaseDesc           string      `json:"release_desc"`
	TestURL               string      `json:"test_url"`
	EnglishName           string      `json:"english_name"`
	Region                string      `json:"region"`
	Level                 string      `json:"level"`
	State                 string      `json:"state"`
	AuditStatus           string      `json:"audit_status"`
	OnlineTime            string      `json:"online_time"`
	OfflineTime           string      `json:"offline_time"`
	IsFirstPublish        string      `json:"is_first_publish"`
	BusinessRefuseReason  interface{} `json:"business_refuse_reason"`
	OldAuditStatus        string      `json:"old_audit_status"`
	ReleaseStatus         string      `json:"release_status"`
	AgeLevel              string      `json:"age_level"`
	NotCompatibleNum      int         `json:"not_compatible_num"`
	Shield                []struct {
		CompatTestID string `json:"compat_test_id"`
		ModelName    string `json:"model_name"`
		ReportURL    string `json:"report_url"`
		State        string `json:"state"`
		ErrorCode    string `json:"error_code"`
		MarketName   string `json:"market_name"`
	} `json:"shield,omitempty"`
	ChangeState            string `json:"change_state"`
	OnlineInfoOfflineApply []struct {
		AppID       string `json:"app_id"`
		VersionID   string `json:"version_id"`
		OnlineState string `json:"online_state"`
		OnlineTime  string `json:"online_time"`
		OfflineTime string `json:"offline_time"`
	} `json:"online_info_offline_apply"`
	FirstOnlineTime         string        `json:"first_online_time"`
	OnlineLevelTag          string        `json:"online_level_tag"`
	Size                    string        `json:"size"`
	AuditStatusName         string        `json:"audit_status_name"`
	OfflineInfo             interface{}   `json:"offline_info,omitempty"`
	TransferState           int           `json:"transfer_state"`
	UpdateInfoCheck         int           `json:"update_info_check"`
	LevelTag                string        `json:"level_tag"`
	RefuseAdvice            string        `json:"refuse_advice"`
	RefuseFile              string        `json:"refuse_file"`
	LevelReason             string        `json:"level_reason"`
	LevelFile               string        `json:"level_file"`
	Revoke                  int           `json:"revoke"`
	IsHasReserve            int           `json:"is_has_reserve"`
	ReserveState            int           `json:"reserve_state"`
	LandscapePicURLMaterial []interface{} `json:"landscape_pic_url_material"`
	PicURLMaterial          []struct {
		URL    string `json:"url"`
		Width  string `json:"width"`
		Height string `json:"height"`
		Md5    string `json:"md5"`
		Size   string `json:"size"`
	} `json:"pic_url_material"`
	VideoURLMaterial []interface{} `json:"video_url_material"`
	PkgSymbol        int           `json:"pkg_symbol"`
	IsReleasePkg     int           `json:"is_release_pkg"`
}

type VerifyInfoResponse struct {
	Errno int `json:"errno"`
	Data  struct {
		AppName           string   `json:"app_name"`
		ApkMd5            string   `json:"apk_md5"`
		MinSdkVersion     int      `json:"min_sdk_version"`
		PackagePermission []string `json:"package_permission"`
		HeaderMd5         string   `json:"header_md5"`
		PkgName           string   `json:"pkg_name"`
		TargetSdkVersion  int      `json:"target_sdk_version"`
		VersionName       string   `json:"version_name"`
		VersionCode       int      `json:"version_code"`
		Sign              string   `json:"sign"`
		ApkSize           int      `json:"apk_size"`
		AllSignList       struct {
			V1 []string `json:"V1"`
			V2 []string `json:"V2"`
		} `json:"all_sign_list"`
		IsSplitApk bool `json:"is_split_apk"`
		Sha1List   []struct {
			V1 string `json:"V1,omitempty"`
			V2 string `json:"V2,omitempty"`
		} `json:"sha1_list"`
		Sha256List []struct {
			V1 string `json:"V1,omitempty"`
			V2 string `json:"V2,omitempty"`
		} `json:"sha256_list"`
		HasLauncher           bool     `json:"has_launcher"`
		CertBase64            string   `json:"cert_base64"`
		PackagePermissionDesc []string `json:"package_permission_desc"`
		NativeCode            string   `json:"native_code"`
		GameMode              string   `json:"game_mode"`
		PaySdkKey             string   `json:"pay_sdk_key"`
		SignV1                string   `json:"sign_v1"`
		SignV2                string   `json:"sign_v2"`
		SignV3                string   `json:"sign_v3"`
		Sha1V1                string   `json:"sha1_v1"`
		Sha1V2                string   `json:"sha1_v2"`
		Sha1V3                string   `json:"sha1_v3"`
		Sha256V1              string   `json:"sha256_v1"`
		Sha256V2              string   `json:"sha256_v2"`
		Sha256V3              string   `json:"sha256_v3"`
		LocalOcsApkURL        string   `json:"local_ocs_apk_url"`
		OriginalSign          string   `json:"original_sign"`
		CheckSkdResult        struct {
			AllianceSdk    []interface{} `json:"alliance_sdk"`
			CooperationSdk []interface{} `json:"cooperation_sdk"`
		} `json:"check_skd_result"`
	} `json:"data"`
}
