name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"
          cache: true
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        continue-on-error: true
        with:
          registry: ghcr.io
          username: KevinGong2013
          password: ${{ secrets.GH_PAT }}
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.GH_PAT }}
